query exerciseSheet($exerciseSheetId: ID!) {
  exerciseSheet(id: $exerciseSheetId) {
    id
    name
    status
    comments {
      ...ExerciseSheetComment
    }
    sheetItems {
      id
      ageGroup
      level
      comments {
        ...ExerciseSheetComment
      }
      exercises {
        id
        order
        comments {
          ...ExerciseSheetComment
        }
        exercise {
          id
          exerciseImage {
            url
          }
          difficulty {
            ageGroup
            difficulty
          }
          description
        }
      }
    }
    createdAt
    updatedAt
    createdBy {
      name
    }
  }
}
