# Deploy to Firebase Hosting DEV on main branch pushes

name: Deploy to Firebase Hosting DEV
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn build
        env:
          VITE_APP_GRAPHQL_ENDPOINT: ${{ vars.VITE_APP_DEV_GRAPHQL_ENDPOINT }}
          VITE_APP_ENDPOINT: ${{ vars.VITE_APP_DEV_ENDPOINT }}
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy to Firebase Hosting DEV
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FELADATSOR_15604 }}' > /tmp/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="/tmp/firebase-service-account.json"
          firebase deploy --only hosting:dev --project feladatsor-15604
