# Deploy to Firebase Hosting DEV on main branch pushes

name: Deploy to Firebase Hosting DEV
"on":
  push:
    branches:
      - main
jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn build
        env:
          VITE_APP_GRAPHQL_ENDPOINT: ${{ vars.VITE_APP_DEV_GRAPHQL_ENDPOINT }}
          VITE_APP_ENDPOINT: ${{ vars.VITE_APP_DEV_ENDPOINT }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FELADATSOR_15604 }}"
          target: dev
          projectId: feladatsor-15604
